// Backend/utils/pdfExporter.js
//
// PDF report generator using PDFKit.
//
// ARCHITECTURE:
//   MongoDB Cursor → PDFKit Doc (stream) → HTTP Response
//
// FEATURES:
//   - Professional header with WasteZero branding
//   - Dynamic tables with column formatting
//   - Automatic page breaks and page numbers
//   - Report footer with timestamp and admin info
//   - Colour-coded status cells
//
// USAGE (in report.service.js):
//   await streamPDF({
//     cursor: User.find(filter).lean().cursor(),
//     res,
//     filename: 'users_report_2026-08-12.pdf',
//     reportTitle: 'Users Report',
//     dateRange: '2026-01-01 → 2026-08-12',
//     generatedBy: 'admin@wastezero.io',
//     columns: [
//       { header: 'Name',   key: 'name',  width: 140 },
//       { header: 'Email',  key: 'email', width: 180 },
//       { header: 'Role',   key: 'role',  width: 80  },
//       { header: 'Status', key: 'isSuspended', width: 60, format: 'bool-status' },
//     ],
//     transform: (doc) => doc,
//   });

const PDFDocument = require('pdfkit');

// ─────────────────────────────────────────────────────────────────────────────
// Brand palette
// ─────────────────────────────────────────────────────────────────────────────
const COLORS = {
  primary:     '#1B5E20', // dark green
  secondary:   '#2E7D32', // medium green
  accent:      '#4CAF50', // bright green
  headerBg:    '#1B5E20',
  headerFg:    '#FFFFFF',
  rowAlt:      '#E8F5E9', // light green alternate row
  rowNormal:   '#FFFFFF',
  border:      '#BDBDBD',
  text:        '#212121',
  subtext:     '#757575',
  success:     '#2E7D32',
  danger:      '#C62828',
  warning:     '#F57F17',
  pageFooter:  '#9E9E9E',
};

const PAGE = {
  margin:    40,
  width:     792, // Letter landscape
  height:    612,
  rowHeight: 22,
  headerH:   26,
};

/**
 * Draw a filled rectangle.
 */
const fillRect = (doc, x, y, w, h, color) => {
  doc.save().rect(x, y, w, h).fill(color).restore();
};

/**
 * Format a cell value based on column type.
 *
 * @param {*} value
 * @param {string} [format]
 * @returns {string}
 */
const formatCellValue = (value, format) => {
  if (value === null || value === undefined) return '—';
  switch (format) {
    case 'bool-status':
      return value ? 'Suspended' : 'Active';
    case 'bool-yn':
      return value ? 'Yes' : 'No';
    case 'date':
      return value instanceof Date
        ? value.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: '2-digit' })
        : String(value).split('T')[0];
    case 'datetime':
      return value instanceof Date
        ? value.toLocaleString('en-US')
        : String(value).replace('T', ' ').replace('Z', '').slice(0, 19);
    case 'number':
      return typeof value === 'number' ? value.toLocaleString() : String(value);
    case 'kg':
      return typeof value === 'number' ? `${value.toFixed(2)} kg` : String(value);
    case 'array':
      return Array.isArray(value) ? value.join(', ') : String(value);
    default:
      return String(value);
  }
};

/**
 * Render the WasteZero PDF report header block.
 *
 * @param {import('pdfkit')} doc
 * @param {object} opts
 */
const drawReportHeader = (doc, { reportTitle, dateRange, generatedBy }) => {
  const { margin, width } = PAGE;
  const contentW = width - margin * 2;

  // Green header bar
  fillRect(doc, margin, margin, contentW, 70, COLORS.headerBg);

  // WasteZero logo text (left)
  doc
    .font('Helvetica-Bold')
    .fontSize(20)
    .fillColor(COLORS.headerFg)
    .text('♻ WasteZero', margin + 16, margin + 14);

  // Platform tagline
  doc
    .font('Helvetica')
    .fontSize(9)
    .fillColor('#A5D6A7')
    .text('Smart Waste Pickup & Recycling Platform', margin + 16, margin + 40);

  // Report title (right side)
  doc
    .font('Helvetica-Bold')
    .fontSize(16)
    .fillColor(COLORS.headerFg)
    .text(reportTitle, margin, margin + 10, {
      width: contentW - 16,
      align: 'right',
    });

  // Subtitle info
  doc
    .font('Helvetica')
    .fontSize(8)
    .fillColor('#C8E6C9')
    .text(
      `Date Range: ${dateRange || 'All time'}   |   Generated by: ${generatedBy || 'Admin'}   |   ${new Date().toUTCString()}`,
      margin,
      margin + 40,
      { width: contentW - 16, align: 'right' }
    );

  doc.moveDown(0.5);
};

/**
 * Draw the column header row for a table.
 *
 * @param {import('pdfkit')} doc
 * @param {{ header: string, width: number }[]} columns
 * @param {number} x
 * @param {number} y
 * @returns {number} Y after header row
 */
const drawTableHeader = (doc, columns, x, y) => {
  let cx = x;
  fillRect(doc, x, y, columns.reduce((sum, c) => sum + c.width, 0), PAGE.headerH, COLORS.headerBg);

  columns.forEach((col) => {
    doc
      .font('Helvetica-Bold')
      .fontSize(8.5)
      .fillColor(COLORS.headerFg)
      .text(col.header, cx + 4, y + 7, {
        width: col.width - 8,
        height: PAGE.headerH - 4,
        ellipsis: true,
        lineBreak: false,
      });
    cx += col.width;
  });

  return y + PAGE.headerH;
};

/**
 * Draw a single data row.
 *
 * @param {import('pdfkit')} doc
 * @param {object} doc_data       - The document
 * @param {{ header, key, width, format }[]} columns
 * @param {number} x
 * @param {number} y
 * @param {boolean} isEven
 * @returns {number} Y after row
 */
const drawTableRow = (doc, doc_data, columns, x, y, isEven) => {
  const totalW = columns.reduce((sum, c) => sum + c.width, 0);

  // Alternate row background
  if (isEven) fillRect(doc, x, y, totalW, PAGE.rowHeight, COLORS.rowAlt);

  let cx = x;
  columns.forEach((col) => {
    const rawVal = col.key.split('.').reduce((obj, k) => obj?.[k], doc_data);
    const text = formatCellValue(rawVal, col.format);

    // Special colour for status columns
    let textColor = COLORS.text;
    if (col.format === 'bool-status') {
      textColor = rawVal ? COLORS.danger : COLORS.success;
    }

    doc
      .font('Helvetica')
      .fontSize(8)
      .fillColor(textColor)
      .text(text, cx + 4, y + 6, {
        width: col.width - 8,
        height: PAGE.rowHeight - 4,
        ellipsis: true,
        lineBreak: false,
      });

    cx += col.width;
  });

  // Row bottom border
  doc
    .save()
    .moveTo(x, y + PAGE.rowHeight)
    .lineTo(x + totalW, y + PAGE.rowHeight)
    .strokeColor('#E0E0E0')
    .lineWidth(0.5)
    .stroke()
    .restore();

  return y + PAGE.rowHeight;
};

/**
 * Draw the page footer with page number.
 *
 * @param {import('pdfkit')} doc
 * @param {number} pageNum
 */
const drawPageFooter = (doc, pageNum) => {
  const { margin, width, height } = PAGE;
  const y = height - margin - 16;

  doc
    .save()
    .moveTo(margin, y)
    .lineTo(width - margin, y)
    .strokeColor(COLORS.border)
    .lineWidth(0.5)
    .stroke()
    .restore();

  doc
    .font('Helvetica')
    .fontSize(7.5)
    .fillColor(COLORS.pageFooter)
    .text('WasteZero Analytics Report — Confidential', margin, y + 4, {
      width: (width - margin * 2) / 2,
      align: 'left',
    })
    .text(`Page ${pageNum}`, margin, y + 4, {
      width: width - margin * 2,
      align: 'right',
    });
};

/**
 * Stream a MongoDB cursor to a PDF HTTP response.
 *
 * @param {object} opts
 * @param {import('mongoose').QueryCursor} opts.cursor
 * @param {import('express').Response}     opts.res
 * @param {string}                         opts.filename
 * @param {string}                         opts.reportTitle
 * @param {string}                         [opts.dateRange]
 * @param {string}                         [opts.generatedBy]
 * @param {{ header, key, width, format? }[]} opts.columns
 * @param {Function}                       [opts.transform]
 * @returns {Promise<void>}
 */
const streamPDF = ({ cursor, res, filename, reportTitle, dateRange, generatedBy, columns, transform }) => {
  return new Promise((resolve, reject) => {
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.setHeader('Cache-Control', 'no-cache');

    const doc = new PDFDocument({
      size:        'LETTER',
      layout:      'landscape',
      margin:      PAGE.margin,
      bufferPages: false, // stream mode — don't buffer
      autoFirstPage: true,
    });

    doc.pipe(res);

    let pageNum      = 1;
    let rowIndex     = 0;
    let currentY;
    const { margin, width, height } = PAGE;
    const usableWidth = width - margin * 2;

    // ── Draw first page header + table header ─────────────────────────────
    drawReportHeader(doc, { reportTitle, dateRange, generatedBy });
    currentY = margin + 70 + 20; // below the header block
    currentY = drawTableHeader(doc, columns, margin, currentY);
    drawPageFooter(doc, pageNum);

    const addPageIfNeeded = () => {
      if (currentY + PAGE.rowHeight > height - margin - 32) {
        drawPageFooter(doc, pageNum);
        doc.addPage();
        pageNum++;
        currentY = margin + 20;
        currentY = drawTableHeader(doc, columns, margin, currentY);
      }
    };

    cursor.on('data', (rawDoc) => {
      try {
        const processed = transform ? transform(rawDoc) : rawDoc;
        addPageIfNeeded();
        const isEven = rowIndex % 2 === 0;
        currentY = drawTableRow(doc, processed, columns, margin, currentY, isEven);
        rowIndex++;
      } catch (err) {
        reject(err);
      }
    });

    cursor.on('error', (err) => {
      doc.end();
      reject(err);
    });

    cursor.on('end', () => {
      try {
        // ── Summary stats block ─────────────────────────────────────────
        if (rowIndex === 0) {
          doc
            .font('Helvetica')
            .fontSize(11)
            .fillColor(COLORS.subtext)
            .text('No records found for the selected date range.', margin, currentY + 20, {
              align: 'center',
              width: usableWidth,
            });
        } else {
          currentY += 16;
          doc
            .font('Helvetica-Oblique')
            .fontSize(8)
            .fillColor(COLORS.subtext)
            .text(
              `Total Records: ${rowIndex}  |  Generated: ${new Date().toUTCString()}  |  WasteZero Analytics Engine v4.0`,
              margin,
              currentY,
              { align: 'center', width: usableWidth }
            );
        }

        drawPageFooter(doc, pageNum);
        doc.end();
        resolve();
      } catch (err) {
        reject(err);
      }
    });

    doc.on('error', reject);
    res.on('error', reject);
    res.on('finish', resolve);
  });
};

module.exports = { streamPDF };
